# Scraping Data from a Real Website + Pandas

https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue

In [ ]:
from bs4 import BeautifulSoup
import requests

In [ ]:
url = 'https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue'

headers = {
    'User-Agent': 'Mozilla/5.0'
}

page = requests.get(url, headers = headers)

soup = BeautifulSoup(page.text, 'html.parser')

In [ ]:
soup.find_all('table')[1]

In [ ]:
soup.find('table', class_ = 'wikitable sortable')

In [ ]:
table = soup.find_all('table')[1]

print(table)

In [ ]:
world_titles = table.find_all('th')

In [ ]:
world_table_titles = [title.text.strip() for title in world_titles]

print(world_table_titles)

In [183]:
import pandas as pd

In [184]:
df = pd.DataFrame(columns = world_table_titles)

df

Empty DataFrame
Columns: [Rank, Name, Industry, Revenue (USD billions), Employees, Headquarters]
Index: []

In [185]:
column_data = table.find_all('tr')

In [186]:
for row in column_data[1:]:
    row_data = row.find_all('td')
    individual_row_data = [data.text.strip() for data in row_data]

    length = len(df)
    df.loc[length] = individual_row_data

In [187]:
df

,Rank,Name,Industry,Revenue (USD billions),Employees,Headquarters
0,1,Cargill,Food industry,154,"155,000","Minnetonka, Minnesota"
1,2,Koch,Multicompany,125,"120,000","Wichita, Kansas"
2,3,Publix Super Markets,Food Markets,59.7,"260,000","Lakeland, Florida"
3,4,Mars,Food & Drink,55,"150,000","McLean, Virginia"
4,5,H-E-B Grocery Company,Food Markets,49.57,"175,000","San Antonio, Texas"
5,6,Reyes Holdings,"Food, Drink & Tobacco",44,"36,000","Rosemont, Illinois"
6,7,Enterprise Mobility,Services,38,"100,000","Clayton, Missouri"
7,8,Fidelity Investments,Insurance,32.7,"78,000","Boston, Massachusetts"
8,9,Southern Glazer's Wine & Spirits,"Food, Drink & Tobacco",25,"24,000","Miramar, Florida"
9,10,Cox Enterprises,Media,23.5,"50,000","Atlanta, Georgia"

In [188]:
df.to_csv(r'C:\Users\Achilleas\Desktop\24_Hour_Course\Python\Companies.csv')